### ISSUE TITLE
Inverse of `existence`?

### ISSUE THREAD

**Issue by dboshardy** [jdkato/txtlint#366]
- macOS
- homebrew
- 2.10.6

I'm wondering if there's a way to ensure certain patterns/tokens **DO** exist in a document. For instance, ensuring there is a heading called "Installation".

Is this possible, if so how?  

I also was wondering if there was a reference for the available fields in style .yaml files. The documentation is missing some field explanations that are in some examples. For instance, `level` or `scope` don't have a list of possible values.

**Comment by jdkato** [comment]
> I'm wondering if there's a way to ensure certain patterns/tokens DO exist in a document. For instance, ensuring there is a heading called "Installation".

Based on #367, I think you've figured this out, but, you can do this with `occurrence` (aforementioned bug notwithstanding). A new release with a fix for #367 will be out soon.

> I also was wondering if there was a reference for the available fields in style .yaml files. The documentation is missing some field explanations that are in some examples. For instance, level or scope don't have a list of possible values.

The supported `level` values are mentioned [here](https://docs.errata.ai/vale/styles#extension-points). The supported `scope` values have their own [dedicated page](https://docs.errata.ai/vale/scoping#types-formats-and-scopes).

**Comment by dboshardy** [comment]
Great, thank you!

**Comment by adam-vest** [comment]
Hi there,

Apologies for posting on an old issue (I can open a new issue if that'd be preferred), but I've been grinding on this exact thing for a while now, and I'm not able to get this kind of search working (ensuring the existence of a heading). I originally asked in discussion #910 , but after continuing to struggle and then finding this (where this functionality presumably existed at least at this time), I'm starting to wonder if there might be a bug, or I'm just lacking the understanding to accomplish this (since OP was apparently sorted at the time). Ideally I'd like to confirm that the heading only occurs exactly once, but I'm not able to get a rule written (that isn't just `raw`) that can confirm the existence of _any_. I would be immensely grateful if someone could point me in the right direction. My rule is:

```
extends: occurrence
message: "Problem description heading does not occur"
ignorecase: true
scope: heading
level: error
min: 1
token: "problem description"
```

Example text:
```
:~$ grep -i "problem description" Documents/example.md
# Problem description
```

Result always triggers:
```
:~$ vale Documents/example.md

 Documents/example.md
 1:1     error    Problem description heading     mine.26a-kb-heading-problem-description 
                  does not occur                         
```

Thanks in advance!

**Comment by jdkato** [comment]
You can't use `scope: heading` for such a task since it restricts the search to *within* each heading when you actually need to search the entire document.

Something like this will work:

```yaml
extends: occurrence
message: "Problem description heading does not occur exactly once"
ignorecase: true
scope: raw.md
level: error
min: 1
max: 1
token: "#{1,} problem description"
```

**Comment by adam-vest** [comment]
@jdkato , thanks for the response! That's what I was afraid of...I actually have markdown and html to factor in, meaning I'll have to write a rule for each heading and for each language to cover the bases. An inelegant solution for sure, but I suppose one I can work with.

I appreciate your time! Thanks :slightly_smiling_face:

**Comment by jdkato** [comment]
It may be possible to do this differently in the future, but it would likely require a new `scope`.
