### ISSUE TITLE
[Feedback Wanted] Vale-related asset management 

### ISSUE THREAD

**Issue by jdkato** [jdkato/txtlint#386]
Easily one of the most discussed aspects of Vale is how to best share, sync, and update its assets (`.vale.ini`, Styles, Vocab, ...).

I've wanting to streamline this process for a while, but I have a few conditions that I'd like to meet:

1. No VCS (Git, submodules, subtrees, ...).
2. No symlinking or other filesystem-dependent methods.
3. It should work for both editor plugins and CI testing.

## The proposal: `packages`

A `package` is simply a `.zip` file that contains a `.vale.ini` file and, optionally, a `StylesPath` directory. That's it.

You can host a `package` anywhere: as a GitHub release asset, on your own domain, as a local file, on a file sharing service, etc.

Using `packages` would look something like this:

```ini
[packages]
# An example of a style-based package. It would include the Microsoft style
# and a `.vale.ini` file that uses it.
Microsoft = <link to release>

# An example of a config-based package. It would only include a `.vale.ini`
# file that defines a configuration relevant for Hugo (such as ignoring
# shortcodes).
Hugo = <link to release>

# An example of both package with a style and configuration specific to
# SomeOrg.
SomeOrg = <link to release>

[SomeOrg]
# override/append configuration to the SomeOrg package.
TokenIgnores = 

[*.md]
Packages = Microsoft, Hugo, SomeOrg
# ^ Package keys are merged; effectively "inheriting" the configuration
# and `StylesPath`. 

# ... normal configuration: all keys merge with inherited packages; it's 
# effectively the local package.
```

This system would allow for sharing, syncing, updating, and overriding of Vale-related assets. All configuration is contained to a single `.vale.ini`, so it would "just work" like a current local configuration (in both editors and CI).

## Feedback

This is probably going to be the single biggest feature introduction in Vale's history, so I'd like to try to get it right.

Please feel free to leave your comments, suggestions, or other ideas entirely.

Related: #176, #273, #348, #384

**Comment by ChrisChinchilla** [comment]
This looks reasonable to me, I'll outline my main use cases of features like this and I think they fit your proposal.

## "Inheritance"

I have a company style guide that uses the pre-packaged Microsoft style guide with some overrides, a style guide for our open source core, and then a commercial product style guide that also overrides some of the open source core style. Added to this, I have other projects that also use the Microsoft style guide and add their own overrides and additional style guides.

1. It would be great to only have one up to date version of the Microsoft style guide on my system.
2. When I share company style guide, it would be great to not have to share other style guide packages with people, and they just "get what they need" somehow.

## Development

More of a niche use case, and closely relates to point 2 above anyway. When I am working on rule sets I have a lot of symlinks to style guides so I can use them in multiple places, but have only one copy of them on disk. I guess the proposal helps with that…


## Thoughts

- Might need some form of version factoring, though I am not sure how much that really matters with Vale style guides really, so "latest" could probably be enough.

> # An example of a style-based package. It would include the Microsoft style
> # and a `.vale.ini` file that uses it.

I'm not completely sure what you mean here, where is the _.vale.ini_ file?

- How do you differentiate the different types of package? Purely on how they are configured? That may get confused, I am not sure.

- I guess this would need some solid explanation on the cascading and merging of overlapping config items to know which would take precedence.


Otherwise, this looks great!

**Comment by jdkato** [comment]
> Might need some form of version factoring, though I am not sure how much that really matters with Vale style guides really, so "latest" could probably be enough.

I think this can be done through the URL. For example, with GitHub releases, you can choose a specific version or use the “latest” redirect. Something similar could be accomplished from any other host too.

> How do you differentiate the different types of package? Purely on how they are configured? That may get confused, I am not sure.

Solely based on the contents. My current idea is to have two cases: only a `.vale.ini` or a `.vale.ini` and a `StylesPath`.

> I guess this would need some solid explanation on the cascading and merging of overlapping config items to know which would take precedence.

This is definitely true. It does feel like a lot will happening “behind the scenes,” so to speak, which could be confusing. The `vale ls-config` command will allow for visualizing the final configuration, which I hope will be a little bit of a help here.

**Comment by themr0c** [comment]
It is a very welcome feature!

The Vale GitHub Action already downloads styles as Zip archives.
It works well for the GitHub Action.
I started to implement a poor man's version of it in this project: https://github.com/eclipse/che-docs/blob/master/tools/get_vale_styles.sh - I can't give a lot of feedback because we just started, but my first impression is that downloading the archives is fast enough.

I am really looking forward to seeing it as a standard Vale CLI behavior.

One question: in the example above, is the `.vale.ini` complete? `StylePath` has a default value that can be omitted?

Would it be possible to apply `Vocab` on a package rather than on all packages?

**Comment by jdkato** [comment]
> The Vale GitHub Action already downloads styles as Zip archives.

Yes, in addition to this, though, packages will allow for configuration inheritance too.

> One question: in the example above, is the `.vale.ini` complete? `StylePath` has a default value that can be omitted?

No, there's no default value for `StylePath`.

> Would it be possible to apply `Vocab` on a package rather than on all packages?

I'm not sure that I understand this question but there are no "required" config sections, so it will be possible to only define a `Vocab` in certain packages.

**Comment by jdkato** [comment]
The first release of this concept will be available soon.
