### ISSUE TITLE
Update GoReleaser script to provide arm64 support.

### ISSUE THREAD

**Issue by faunaee** [jdkato/txtlint#418]
The script at `https://install.goreleaser.com/github.com/ValeLint/vale.sh` includes this code:

```
 get_binaries() {
  case "$PLATFORM" in
    darwin/amd64) BINARIES="vale" ;;
    linux/amd64) BINARIES="vale" ;;
    windows/amd64) BINARIES="vale" ;;
    *)
      log_crit "platform $PLATFORM is not supported.  Make sure this script is up-to-date and file request at https://github.com/${PREFIX}/issues/new"
      exit 1
      ;;
  esac
}
```

That logic appears to be what is preventing the recently-added arm64 build from being installed. I'm not sure where that script comes from, but it would be great if it could be updated!

**Comment by jdkato** [comment]
The GoDownloader project has been deprecated and is no longer maintained.

You can use the GitHub CLI (as [shown here](https://github.com/errata-ai/vale/releases/tag/v2.11.2)) or another utility (such as `curl` / `wget`) to download the release.

**Comment by faunaee** [comment]
Ah, I missed that release note. I'll update my CI steps to use `curl`. Thanks!

**Comment by Mahesh8** [comment]
@jdkato How do I install vale with `curl`. Can you provide the command or relevant docs to install and run vale then?

**Comment by eskwayrd** [comment]
@Mahesh8 Here are steps that should work. Feel free to modify to suit your needs:

1. Go to Vale's release page: https://github.com/errata-ai/vale/releases
2. Choose the version/archive you want to download.
3. Right-click that link, and choose "Copy link"
4. In a terminal, type `curl -L `, then paste the URL that you copied, then type ` -o vale.tgz`
   Note: If you are downloading the `.zip` archive, use `.zip` instead of `.tgz` after the `-o`.
5. Extract the files from the archive:
   For `vale.tgz`, use: `tar zxf vale.tgz`
   For `vale.zip`, use: `unzip vale.zip`.
6. Each archive contains the files `LICENSE`, `README.md`, and the binary `vale` (`vale.exe` in the `.zip` archive).
   Move that binary to where it needs to exist on your system.
7. Run the binary.
