### ISSUE TITLE
Custom tokenizer regexp

### ISSUE THREAD

**Issue by lekcyjna123** [jdkato/txtlint#435]
Hi,

I try to add spelling checking to python source code files, which has a lot of doc strings. But to do that I have to be able to filter out variable names from being checked by spellchecker. For exmaple: `example_long_variable` and \`variableInBackticks\`.

In my opinion simplest way will be to ignore anything inside \`\` or having "_". I see that in https://github.com/errata-ai/vale/issues/263 there is info that there is no other processing inside of block comments and in code I see that spellchecking rules get words created by tokenizer with hardcoded tokenizer regexp:
https://github.com/errata-ai/vale/blob/d1891675adee2994b3cda6f0f8ad2ec2a70c4b6e/internal/nlp/prose.go#L18-L19

So my idea is to add possibility of passing tokenizer regexp as a parameter to vale. Having custom tokenizer there will be possibility to change tokenization in such way, that `example_long_variable` and \`variableInBackticks\` will be one token, which can be next filtered out by spelling rules.

What do you think about that idea? Would you be ready to accept merge request which will be adding such functionality?

**Comment by jdkato** [comment]
I think ideally we should address this by adding the ability to process embedded markup -- such as [Markdown in Rust](https://doc.rust-lang.org/rust-by-example/meta/doc.html#doc-comments), [reStructuredText in Python](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#field-lists), or any other combination.

Since Vale is already quite good at handling markup on its own (e.g., ignoring backticks), it's really just a matter of extracting comments and assigning a format.

#249 and #263 are related issues.
