### ISSUE TITLE
Allow linting files with a single style or a subset of styles

### ISSUE THREAD

**Issue by MLNW** [jdkato/txtlint#466]
It would be great if one could run vale on files and provide either a single style or a subset of styles to apply.

This would help in testing new styles and allows creating reports for a specific violation.

AFAIK this option is currently not available. I guess one could work around it by creating a specific configuration for running a specific style but that is quite cumbersome in comparison to providing styles as command line options.

**Comment by jdkato** [comment]
> AFAIK this option is currently not available.

It isn't currently available, but the implementation here should probably be similar to the current `--minAlertLevel` flag.

**Comment by amyq** [comment]
A teammate just asked me a similar question. To do this, currently, I cheat a bit. I know that our docset has no `error`-level violations (because we break CI on those), so I manually set the one rule to `error` and then run vale against the entire docset with a minimum level of `error`. Hacky, but gets the job done.

We'd definitely use this option if it were baked in. At times, we pick one rule and work on burning down the number of results for just that one rule.

**Comment by jdkato** [comment]
This is possible now in [`v2.23.0`](https://github.com/errata-ai/vale/releases/tag/v2.23.0).
